# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pqueue/all/pqueue.rbi
#
# pqueue-2.1.0

class PQueue
  def <<(v); end
  def ==(other); end
  def binary_index(que, target); end
  def bottom; end
  def clear; end
  def cmp; end
  def concat(elements); end
  def deq; end
  def each_pop; end
  def empty?; end
  def enq(v); end
  def heapify; end
  def include?(element); end
  def initialize(elements = nil, &block); end
  def initialize_copy(other); end
  def inspect; end
  def length; end
  def merge!(elements); end
  def peek; end
  def pop; end
  def push(v); end
  def que; end
  def reheap(k); end
  def replace(elements); end
  def shift; end
  def size; end
  def sort!; end
  def swap(v); end
  def take(n = nil); end
  def to_a; end
  def top; end
end
