# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/random_name_generator/all/random_name_generator.rbi
#
# random_name_generator-1.2.1

class RNGSyllable
  def compatible?(next_syllable); end
  def consonant_first?; end
  def consonant_last?; end
  def incompatible?(next_syllable); end
  def initialize(args); end
  def next_incompatible?(next_syllable); end
  def next_syllable_must_start_with_consonant?; end
  def next_syllable_must_start_with_vowel?; end
  def next_syllable_requirement; end
  def next_syllable_universal?; end
  def parse_args(args); end
  def parse_flags(flags); end
  def parse_prefix(prefix); end
  def parse_syllable(syll); end
  def prefix?; end
  def previous_incompatible?(next_syllable); end
  def previous_syllable_must_end_with_consonant?; end
  def previous_syllable_must_end_with_vowel?; end
  def previous_syllable_requirement; end
  def previous_syllable_universal?; end
  def raw; end
  def suffix?; end
  def syllable; end
  def to_s; end
  def to_str; end
  def vowel_first?; end
  def vowel_last?; end
end
class RandomNameGenerator
  def compose(count = nil); end
  def determine_last_syllable(next_to_last_syllable); end
  def determine_middle_syllables(count, pre); end
  def determine_next_syllable(this_syllable, sampler); end
  def determine_next_syllables(count, pre, syllables); end
  def initialize(filename = nil, random: nil); end
  def mid_syllables; end
  def pre; end
  def pre_syllables; end
  def refresh; end
  def self.flip_mode; end
  def self.flip_mode_cyrillic; end
  def self.pick_number_of_syllables; end
  def sur_syllables; end
  def to_s; end
end
