# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/strings-ansi/all/strings-ansi.rbi
#
# strings-ansi-0.2.0

module Strings
end
module Strings::ANSI
  def ansi?(string); end
  def only_ansi?(string); end
  def sanitize(string); end
  def self.ansi?(string); end
  def self.only_ansi?(string); end
  def self.sanitize(string); end
end
