# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicode_utils/all/unicode_utils.rbi
#
# unicode_utils-1.4.0

module UnicodeUtils
  def each_grapheme(str); end
  def self.each_grapheme(str); end
end
module UnicodeUtils::Impl
  def self.open_cdata_file(filename, &block); end
  def self.read_code_point_map(filename); end
  def self.read_code_point_set(filename); end
  def self.read_combining_class_map; end
  def self.read_conditional_casings(filename); end
  def self.read_east_asian_width_per_cp(filename); end
  def self.read_east_asian_width_ranges(filename); end
  def self.read_general_category_per_cp(filename); end
  def self.read_general_category_ranges(filename); end
  def self.read_hexdigit_map(filename); end
  def self.read_multivalued_map(filename); end
  def self.read_name_aliases(filename); end
  def self.read_names(filename); end
  def self.read_range_to_hexdigit_list(filename); end
  def self.read_symbol_map(filename); end
end
